import React, { useState, useEffect } from 'react';
import { View, StyleSheet, TouchableOpacity, Text, Alert, Modal, TextInput } from 'react-native';
import { useRoute, useNavigation } from '@react-navigation/native';
import * as FileSystem from 'expo-file-system';
import CodeEditor from '../components/CodeEditor';
import { Save, GitBranch, Terminal, Settings } from 'lucide-react-native';
import { EditorScreenRouteProp, EditorScreenNavigationProp } from '../navigation/types';

export default function EditorScreen() {
  const route = useRoute<EditorScreenRouteProp>();
  const navigation = useNavigation<EditorScreenNavigationProp>();
  const { filename, newFile } = route.params || {};
  const [code, setCode] = useState('// Write your code here...');
  const [language, setLanguage] = useState('javascript');
  const [theme, setTheme] = useState<'vs-dark' | 'vs-light'>('vs-dark');
  const [isAiModalVisible, setIsAiModalVisible] = useState(false);
  const [aiPrompt, setAiPrompt] = useState('');

  useEffect(() => {
    if (filename) {
      loadFile(filename);
      detectLanguage(filename);
    }
  }, [filename]);

  const loadFile = async (file: string) => {
    try {
      const content = await FileSystem.readAsStringAsync(((FileSystem as any).documentDirectory || '') + 'projects/' + file);
      setCode(content);
    } catch (e) {
      Alert.alert('Error', 'Failed to load file');
    }
  };

  const detectLanguage = (file: string) => {
    const ext = file.split('.').pop();
    switch (ext) {
      case 'js': setLanguage('javascript'); break;
      case 'ts': setLanguage('typescript'); break;
      case 'py': setLanguage('python'); break;
      case 'html': setLanguage('html'); break;
      case 'css': setLanguage('css'); break;
      case 'json': setLanguage('json'); break;
      case 'java': setLanguage('java'); break;
      case 'cpp': setLanguage('cpp'); break;
      default: setLanguage('plaintext');
    }
  };

  const handleSave = async () => {
    if (!filename && !newFile) return;
    const name = filename || 'untitled.js'; // TODO: Ask for filename if new
    try {
      await FileSystem.writeAsStringAsync(((FileSystem as any).documentDirectory || '') + 'projects/' + name, code);
      Alert.alert('Success', 'File saved');
    } catch (e) {
      Alert.alert('Error', 'Failed to save file');
    }
  };

  const handleAiGenerate = () => {
    // Mock AI generation
    setIsAiModalVisible(false);
    const mockCode = `\n// Generated by AI for: ${aiPrompt}\nfunction aiGenerated() {\n  console.log("AI Magic!");\n}`;
    setCode(prev => prev + mockCode);
  };

  return (
    <View style={styles.container}>
      <View style={styles.toolbar}>
        <TouchableOpacity onPress={handleSave} style={styles.toolButton}>
          <Save color="#333" size={24} />
        </TouchableOpacity>
        <TouchableOpacity onPress={() => setIsAiModalVisible(true)} style={styles.toolButton}>
          <Terminal color="#333" size={24} />
        </TouchableOpacity>
        <TouchableOpacity onPress={() => navigation.navigate('Git')} style={styles.toolButton}>
          <GitBranch color="#333" size={24} />
        </TouchableOpacity>
        <TouchableOpacity onPress={() => navigation.navigate('Settings')} style={styles.toolButton}>
          <Settings color="#333" size={24} />
        </TouchableOpacity>
      </View>
      
      <CodeEditor 
        initialCode={code} 
        language={language} 
        onChange={setCode} 
        theme={theme}
      />

      <Modal visible={isAiModalVisible} animationType="slide" transparent>
        <View style={styles.modalContainer}>
          <View style={styles.modalContent}>
            <Text style={styles.modalTitle}>AI Code Generator (Paid Feature)</Text>
            <TextInput
              style={styles.aiInput}
              placeholder="Describe what you want..."
              value={aiPrompt}
              onChangeText={setAiPrompt}
              multiline
            />
            <View style={styles.modalButtons}>
              <TouchableOpacity onPress={() => setIsAiModalVisible(false)} style={styles.cancelButton}>
                <Text>Cancel</Text>
              </TouchableOpacity>
              <TouchableOpacity onPress={handleAiGenerate} style={styles.generateButton}>
                <Text style={{color: 'white'}}>Generate</Text>
              </TouchableOpacity>
            </View>
          </View>
        </View>
      </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  toolbar: {
    flexDirection: 'row',
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    justifyContent: 'space-around',
  },
  toolButton: {
    padding: 8,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
    padding: 20,
  },
  modalContent: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  aiInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    padding: 10,
    height: 100,
    marginBottom: 20,
    borderRadius: 5,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  cancelButton: {
    padding: 10,
    marginRight: 10,
  },
  generateButton: {
    padding: 10,
    backgroundColor: '#007bff',
    borderRadius: 5,
  },
});
